metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: all
  anno_path: detection_annotations/semantic_bbox_train.json
  dataset_dir: datasets/spine_fracture/drr
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: test
  anno_path: detection_annotations/semantic_bbox_val.json
  dataset_dir: datasets/spine_fracture/drr
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: detection_annotations/semantic_bbox_test.json # also support txt (like VOC's label_list.txt)
  dataset_dir: datasets/spine_fracture/drr # if set, anno_path will be 'dataset_dir/anno_path'
